[package]
name = "bgp-parser"
version = "0.1.0"
description = "Parser for the BGP version 4"
license = "MIT/Apache-2.0"
authors = ["Kunihiro Ishiguro <kunihiro@zebra.dev>"]
edition = "2018"

[dependencies]
nom = "6"
rusticata-macros = "3.0"

[dev-dependencies]
hex-literal = "0.3"
